version: '3.8'

services:

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=projeto
      - DB_INIT_RETRIES=20
      - DB_INIT_RETRY_DELAY_MS=3000
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mailhog
      - database
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: azis_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d projeto" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  frontend_node_modules:
  backend_node_modules:
